// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLB) DeepCopyInto(out *CLB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLB.
func (in *CLB) DeepCopy() *CLB {
	if in == nil {
		return nil
	}
	out := new(CLB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CLB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBList) DeepCopyInto(out *CLBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CLB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBList.
func (in *CLBList) DeepCopy() *CLBList {
	if in == nil {
		return nil
	}
	out := new(CLBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CLBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBObservation) DeepCopyInto(out *CLBObservation) {
	*out = *in
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.NetworkType != nil {
		in, out := &in.NetworkType, &out.NetworkType
		*out = new(string)
		**out = **in
	}
	if in.MasterZoneID != nil {
		in, out := &in.MasterZoneID, &out.MasterZoneID
		*out = new(string)
		**out = **in
	}
	if in.ModificationProtectionReason != nil {
		in, out := &in.ModificationProtectionReason, &out.ModificationProtectionReason
		*out = new(string)
		**out = **in
	}
	if in.ModificationProtectionStatus != nil {
		in, out := &in.ModificationProtectionStatus, &out.ModificationProtectionStatus
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerStatus != nil {
		in, out := &in.LoadBalancerStatus, &out.LoadBalancerStatus
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupID != nil {
		in, out := &in.ResourceGroupID, &out.ResourceGroupID
		*out = new(string)
		**out = **in
	}
	if in.DeleteProtection != nil {
		in, out := &in.DeleteProtection, &out.DeleteProtection
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBObservation.
func (in *CLBObservation) DeepCopy() *CLBObservation {
	if in == nil {
		return nil
	}
	out := new(CLBObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBParameter) DeepCopyInto(out *CLBParameter) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.AddressType != nil {
		in, out := &in.AddressType, &out.AddressType
		*out = new(string)
		**out = **in
	}
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Bandwidth != nil {
		in, out := &in.Bandwidth, &out.Bandwidth
		*out = new(int32)
		**out = **in
	}
	if in.InternetChargeType != nil {
		in, out := &in.InternetChargeType, &out.InternetChargeType
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.VpcID != nil {
		in, out := &in.VpcID, &out.VpcID
		*out = new(string)
		**out = **in
	}
	if in.VSwitchID != nil {
		in, out := &in.VSwitchID, &out.VSwitchID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerSpec != nil {
		in, out := &in.LoadBalancerSpec, &out.LoadBalancerSpec
		*out = new(string)
		**out = **in
	}
	if in.ClientToken != nil {
		in, out := &in.ClientToken, &out.ClientToken
		*out = new(string)
		**out = **in
	}
	if in.OwnerID != nil {
		in, out := &in.OwnerID, &out.OwnerID
		*out = new(int64)
		**out = **in
	}
	if in.ResourceOwnerAccount != nil {
		in, out := &in.ResourceOwnerAccount, &out.ResourceOwnerAccount
		*out = new(string)
		**out = **in
	}
	if in.ResourceOwnerID != nil {
		in, out := &in.ResourceOwnerID, &out.ResourceOwnerID
		*out = new(int64)
		**out = **in
	}
	if in.OwnerAccount != nil {
		in, out := &in.OwnerAccount, &out.OwnerAccount
		*out = new(string)
		**out = **in
	}
	if in.MasterZoneID != nil {
		in, out := &in.MasterZoneID, &out.MasterZoneID
		*out = new(string)
		**out = **in
	}
	if in.SlaveZoneID != nil {
		in, out := &in.SlaveZoneID, &out.SlaveZoneID
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupID != nil {
		in, out := &in.ResourceGroupID, &out.ResourceGroupID
		*out = new(string)
		**out = **in
	}
	if in.PayType != nil {
		in, out := &in.PayType, &out.PayType
		*out = new(string)
		**out = **in
	}
	if in.PricingCycle != nil {
		in, out := &in.PricingCycle, &out.PricingCycle
		*out = new(string)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(int32)
		**out = **in
	}
	if in.AutoPay != nil {
		in, out := &in.AutoPay, &out.AutoPay
		*out = new(bool)
		**out = **in
	}
	if in.AddressIPVersion != nil {
		in, out := &in.AddressIPVersion, &out.AddressIPVersion
		*out = new(string)
		**out = **in
	}
	if in.DeleteProtection != nil {
		in, out := &in.DeleteProtection, &out.DeleteProtection
		*out = new(string)
		**out = **in
	}
	if in.ModificationProtectionStatus != nil {
		in, out := &in.ModificationProtectionStatus, &out.ModificationProtectionStatus
		*out = new(string)
		**out = **in
	}
	if in.ModificationProtectionReason != nil {
		in, out := &in.ModificationProtectionReason, &out.ModificationProtectionReason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBParameter.
func (in *CLBParameter) DeepCopy() *CLBParameter {
	if in == nil {
		return nil
	}
	out := new(CLBParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBSpec) DeepCopyInto(out *CLBSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBSpec.
func (in *CLBSpec) DeepCopy() *CLBSpec {
	if in == nil {
		return nil
	}
	out := new(CLBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBStatus) DeepCopyInto(out *CLBStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBStatus.
func (in *CLBStatus) DeepCopy() *CLBStatus {
	if in == nil {
		return nil
	}
	out := new(CLBStatus)
	in.DeepCopyInto(out)
	return out
}
