apiVersion: oss.alibaba.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: example-oss-bucket
spec:
  acl: private
  storageClass: Standard
  dataRedundancyType: LRS
  writeConnectionSecretToRef:
    name: example-oss
    namespace: default
