apiVersion: sls.alibaba.crossplane.io/v1alpha1
kind: MachineGroup
metadata:
  name: sls-machinegroup-test
spec:
  forProvider:
    project: crossplane-poc
    logstore: sls-store-test
    machineIDType: userdefined
    machineIDList:
      - "192.168.2.1"
      - "192.168.2.2"
    attribute:
      externalName: testgroup
      groupTopic: testtopic
  writeConnectionSecretToRef:
    name: sls-machinegroup
    namespace: default
