---
apiVersion: database.alibaba.crossplane.io/v1alpha1
kind: RDSInstance
metadata:
  name: example
  labels:
    example: "true"
    engine: mysql
spec:
  forProvider:
    engine: mysql
    engineVersion: "8.0"
    dbInstanceClass: "rds.mysql.c1.large"
    dbInstanceStorageInGB: 20
    securityIPList: "0.0.0.0/0"
    masterUsername: "test123"
    networkType: CLASSIC
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: example-rds
  providerConfigRef:
    name: default
  deletionPolicy: Delete
